name: "JS Actions"

on:
  pull_request:
    types: [labeled]

jobs:
  action:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1

      - name: "hello-action"
        uses: ./.github/actions/hello-world
        with:
          first-greeting: "First"
          second-greeting: "Second"
          third-greeting: "Third"
      
      - name: ha-ha
        uses: ./.github/actions/joke-action
        id: jokes
      
      - name: create issue
        uses: ./.github/actions/issue-maker
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          joke: ${{steps.jokes.outputs.joke-output}}
      
      - name: TypeScript Action
        uses: ./.github/actions/typescript-action
        with:
          milliseconds: 1000